// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocalWallpapersJSON(arg1:string):Promise<string>;

export function GetWallpaperBase64(arg1:string):Promise<string>;

export function GetWallpaperPath():Promise<string>;

export function Greet(arg1:string):Promise<string>;
