// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFileExists(arg1:string):Promise<boolean>;

export function GetLocalWallpapersJSON(arg1:string):Promise<string>;

export function GetWallpaperBase64(arg1:string):Promise<string>;

export function GetWallpaperPath():Promise<string>;

export function SetWallpaper(arg1:string):Promise<void>;
