// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWallpaperBase64(arg1) {
  return window['go']['main']['App']['GetWallpaperBase64'](arg1);
}

export function GetWallpaperPath() {
  return window['go']['main']['App']['GetWallpaperPath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
