// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFileExists(arg1) {
  return window['go']['main']['App']['CheckFileExists'](arg1);
}

export function GetLocalWallpapersJSON(arg1) {
  return window['go']['main']['App']['GetLocalWallpapersJSON'](arg1);
}

export function GetWallpaperBase64(arg1) {
  return window['go']['main']['App']['GetWallpaperBase64'](arg1);
}

export function GetWallpaperPath() {
  return window['go']['main']['App']['GetWallpaperPath']();
}

export function SetWallpaper(arg1) {
  return window['go']['main']['App']['SetWallpaper'](arg1);
}
